In [1]:
import numpy as np

# DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [10]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.6]])
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [5]:
a3

array([[list([1, 2, 3]), list([4, 5, 6]), list([7, 8, 9])],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]], dtype=object)

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [11]:
a3.shape

(2, 3, 3)

In [12]:
# Dimension of matrix
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [13]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [14]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [15]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Creating a DataFrame from a Numpy array

In [20]:
import pandas as pd
df = pd.DataFrame(a2) # NOT Series!!! With DataFrame()!
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

# Creating arrays

In [21]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [22]:
sample_array.dtype

dtype('int32')

In [24]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [25]:
ones.dtype

dtype('float64')

In [26]:
type(ones)

numpy.ndarray

In [30]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [31]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [33]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[0, 2, 2, 6, 5],
       [3, 6, 2, 1, 9],
       [3, 9, 1, 9, 8]])

In [34]:
random_array.size

15

In [35]:
random_array.shape

(3, 5)

In [43]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.37750288, 0.95683907, 0.07794578],
       [0.44973155, 0.61605928, 0.69183036],
       [0.24461337, 0.40163956, 0.61712434],
       [0.71245229, 0.9559018 , 0.57038273],
       [0.95188228, 0.3251534 , 0.95615582]])

In [44]:
random_array_2.shape

(5, 3)

In [45]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.18465207, 0.66483845, 0.66716391],
       [0.39606435, 0.74206892, 0.93250927],
       [0.10531612, 0.16646879, 0.26316098],
       [0.02292706, 0.72418403, 0.06894558],
       [0.96932351, 0.60118407, 0.52947662]])

In [46]:
# Pseudo-random numbers
# np.random.seed()
random_array_4 = np.random.randint