In [1]:
import numpy as np

# DataTypes & Attributes

In [2]:
# Numpy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
              [4, 5, 6.6]])
a3 = np.array([[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9]],
              [[10, 11, 12],
              [13, 14, 15],
              [16, 17, 18]]])
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.6]])

In [5]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [6]:
a1.shape

(3,)

In [7]:
a2.shape

(2, 3)

In [8]:
a3.shape

(2, 3, 3)

In [9]:
# Dimension of matrix
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [10]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [11]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [12]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

# Creating a DataFrame from a Numpy array

In [13]:
import pandas as pd
df = pd.DataFrame(a2) # NOT Series!!! With DataFrame()!
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.6

# Creating arrays

In [14]:
sample_array = np.array([1, 2, 3])
sample_array

array([1, 2, 3])

In [15]:
sample_array.dtype

dtype('int32')

In [16]:
ones = np.ones((2, 3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [17]:
ones.dtype

dtype('float64')

In [18]:
type(ones)

numpy.ndarray

In [19]:
zeros = np.zeros((3, 3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [21]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[7, 9, 1, 0, 3],
       [2, 2, 7, 8, 7],
       [8, 2, 3, 1, 2]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.7599144 , 0.86705258, 0.46960772],
       [0.7012695 , 0.02767951, 0.9281636 ],
       [0.43052377, 0.63747589, 0.02217071],
       [0.96501356, 0.56241696, 0.08626057],
       [0.67190689, 0.35199604, 0.55427475]])

In [25]:
random_array_2.shape

(5, 3)

In [26]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.58344573, 0.58310245, 0.85221253],
       [0.54965511, 0.30420005, 0.78129798],
       [0.71942408, 0.52261841, 0.73778967],
       [0.59506397, 0.01801827, 0.15242163],
       [0.53420096, 0.0666557 , 0.12892821]])

In [123]:
# Pseudo-random numbers
np.random.seed(7)
random_array_4 = np.random.random((3, 5))
random_array_4
# random.seed(int) function keeps the random numbers same.

array([[0.07630829, 0.77991879, 0.43840923, 0.72346518, 0.97798951],
       [0.53849587, 0.50112046, 0.07205113, 0.26843898, 0.4998825 ],
       [0.67923   , 0.80373904, 0.38094113, 0.06593635, 0.2881456 ]])

# Viewing arrays and matrices

In [30]:
np.unique(random_array)

array([0, 1, 2, 3, 7, 8, 9])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a3[0][1]

array([4, 5, 6])

In [37]:
a3[0][1][0]

4

In [41]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [42]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [63]:
a3[:2, :1, :2]

array([[[ 1,  2]],

       [[10, 11]]])

In [84]:
np.random.seed(4)
a4 = np.random.randint(0, 2, size=(4, 3, 3))
a4

array([[[0, 0, 1],
        [1, 1, 0],
        [1, 0, 0]],

       [[1, 0, 0],
        [1, 1, 0],
        [1, 1, 1]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 1]],

       [[0, 1, 1],
        [1, 1, 0],
        [1, 0, 0]]])

In [86]:
a4[:4,:1,:3] #every first line

array([[[0, 0, 1]],

       [[1, 0, 0]],

       [[0, 0, 0]],

       [[0, 1, 1]]])

In [88]:
a4[:4, :2, :3]

array([[[0, 0, 1],
        [1, 1, 0]],

       [[1, 0, 0],
        [1, 1, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 1, 1],
        [1, 1, 0]]])

# Arithmetic Operations

In [104]:
np.random.seed(4)
x1 = np.random.randint(4, size=(1, 3))
np.random.seed(3)
x2 = np.random.randint(4, size=(1, 3))
np.random.seed(2)
diff = np.random.randint(4, size=(1, 4))
diff, x1, x2

(array([[0, 3, 1, 0]]), array([[2, 2, 3]]), array([[2, 0, 1]]))

In [98]:
x1 + x2

array([[4, 2, 4]])

In [99]:
x1-x2

array([[0, 2, 2]])

In [100]:
x1*x2

array([[4, 0, 3]])

In [102]:
x2/x1

array([[1.        , 0.        , 0.33333333]])

# Let's try with different shape of matrices

In [105]:
x1+diff

ValueError: operands could not be broadcast together with shapes (1,3) (1,4) 

In [106]:
x2-diff

ValueError: operands could not be broadcast together with shapes (1,3) (1,4) 

In [107]:
x2*diff

ValueError: operands could not be broadcast together with shapes (1,3) (1,4) 

# :(

# Aggregation
Aggregation = performing the same operation on a number of things

In [108]:
list = [1, 2, 3, 4]
list

[1, 2, 3, 4]

In [109]:
sum(list)

10

In [110]:
type(list)

list

In [111]:
a1

array([1, 2, 3])

In [112]:
sum(a1)

6

In [114]:
np.sum(a1)

6

In [121]:
type(a1)

numpy.ndarray

Same right? We have to use `sum()` for Python datatypes and `np.sum()` for numpy datatypes. Let's see the difference.

In [124]:
massive = np.random.random(100000)
massive[:10]

array([0.90959353, 0.21338535, 0.45212396, 0.93120602, 0.02489923,
       0.60054892, 0.9501295 , 0.23030288, 0.54848992, 0.90912837])

In [125]:
%timeit sum(massive) #Python's sum()
%timeit np.sum(massive) #NumPy's np.sum()

10.9 ms ± 155 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
71.4 µs ± 470 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)
